### ISSUE TITLE
Animation Mask

### ISSUE THREAD

**Issue by tobybonhof** [christophesmet/android_maskable_layout#2]
How does one easily create an animation mask?

**Comment by christophesmet** [comment]
Check the sample code here:
https://github.com/christophesmet/android_maskable_layout/tree/master/Sample/src/main/res/drawable
There you can see an animation drawable in xml.
Then just pass that drawable in xml as the mask.
Thats all :)

**Comment by tanab** [comment]
Yes but i mean there are like 60+ states defined. Are these states manually created or generated somehow. Or is it possible to define a begin state and an end state and the mask automatically morphs to the end state?

**Comment by christophesmet** [comment]
The images are generated in photoshop but manually defined in xml.
I don't think there is a tool out there for it.
However, since Android L there is native svg support with svg animations: AnimatedVectorDrawable
The maskable layout only masks, the morphing should be done by the drawable.
If you extend the drawable class and make it morphe, then it will work automatically.
I'd love to see the MorphingDrawable class though :)
